language: python
python:
    - 3.5
    - 3.6
    - 3.7

install:
    pip install coveralls

script:
    coverage run -m --source=/home/travis/build/franelias/bingo/src pytest

after_success:
    coveralls
